In [ ]:
import os
import sys

sys.path.append("/data/zhangyufeng/Rec/dl-based")

In [ ]:
import pandas as pd


def _load_df_parquet(data_path) -> pd.DataFrame:
    df = pd.read_parquet(data_path)
    return df

In [2]:
df = _load_df_parquet("/data/zhangyufeng/Rec/data/criteo_data_with_interactions.parquet")

In [3]:
df

,Label,C_1,C_2,C_3,C_4,C_5,C_6,C_7,C_8,C_9,...,I_24,I_25,I_26,I_22_x_I_23,I_22_x_I_24,I_11_x_I_13,I_12_x_I_16,I_14_x_I_15,I_15_x_I_18,I_1_x_I_7
987231,0,0.000000,5,5.000000,1.000000,8680.0,115.967765,16.378482,15.0,105.970785,...,95196,0,18181,20,96169,2733,658829,6667,4414,103315
79954,0,0.000000,7,7.000000,1.000000,2060.0,63.000000,24.000000,16.0,225.000000,...,26531,1,49859,22,23209,4195,1044467,8097,8685,225122
567130,0,0.000000,0,26.869474,12.000000,21133.0,616.000000,1.000000,25.0,272.000000,...,54896,0,18181,21,53369,5064,619196,6153,2830,126909
500891,0,0.000000,4,5.000000,3.000000,2088.0,115.967765,0.000000,3.0,2.000000,...,8845,80,46213,21,88994,2344,964892,5526,1097,98474
55399,0,3.508343,2,1.000000,5.000000,311411.0,115.967765,0.000000,7.0,29.000000,...,22464,0,18181,16,18863,4272,843634,3401,10271,103530
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45397131,1,0.000000,57,4.000000,9.000000,1416.0,363.000000,3.000000,21.0,162.000000,...,54407,0,18181,21,52854,1825,434015,1072,2453,106133
45442753,0,3.508343,-1,26.869474,7.327777,37634.0,115.967765,0.000000,1.0,19.000000,...,46942,83,12695,21,44941,4817,477837,4593,4445,53049
45699432,0,3.508343,0,20.000000,7.000000,7377.0,34.000000,49.000000,8.0,33.000000,...,41168,83,31417,21,38788,2265,1152302,9172,11954,143078
45751041,0,0.000000,0,26.869474,7.327777,692.0,4.000000,6.000000,1.0,73.000000,...,22464,0,18181,22,18863,2766,57279,7842,7891,102055
45339880,1,0.000000,8,39.000000,8.000000,1759.0,115.000000,63.000000,7.0,548.000000,...,64728,60,18580,16,63812,1399,974420,10661,8688,100527

In [4]:
interaction_cols = [col for col in df.columns if "x_I" in col]
interaction_cols

['I_22_x_I_23',
 'I_22_x_I_24',
 'I_11_x_I_13',
 'I_12_x_I_16',
 'I_14_x_I_15',
 'I_15_x_I_18',
 'I_1_x_I_7']

In [1]:
import torch

In [9]:
W = torch.randn(100, 39, 39)
hadamard = torch.randn(32, 39, 39, 16)
# hadamard: [B, C, N, D] | W: [F, C, N]
# out shape's [batch_size, feature_maps, cin_hidden_size, embed_dim]
out = torch.einsum("b c n d, f c n -> b f c d", hadamard, W)

In [10]:
out.shape

torch.Size([32, 100, 39, 16])